### ISSUE TITLE
Using "requireCordovaModule" to load non-cordova module "glob" is not supported.

### ISSUE THREAD

**Issue by dacape-dev** [jellomaster/cordova-plugin-google-ump#1]
Hi!

When installing the plugin I have the following error:

`Using "requireCordovaModule" to load non-cordova module "glob" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
[ERROR] An error occurred while running subprocess cordova.`

I have read that it is because it is not compatible with cordova 9.

Thanks in advance!

**Comment by jellomaster** [comment]
Issue should be fixed in the latest version
